import { EditorState } from '@codemirror/state';
import { describe, expect, it } from 'vitest';
import { citationDocument, parseCitationDocument } from './citationDocument';
import { extractCitations } from './citations';
import { documentLanguageHint } from './documentBudget';
import { detectBiblioStyle, planBiblioEdit } from './bibliography';

describe('one citation model for prose and native document languages', () => {
  it('retains document order and counts while excluding Markdown examples, metadata, comments, links and formulas', () => {
    const source = [
      '---', 'title: "@metadata"', '---',
      '[@second; @first] and @second.', '',
      '`[@inline]`', '', '```md', '[@fenced]', '<!-- biblio:apa -->', '```', '',
      '    [@indented]', '', '<!-- @comment -->', '[mail user@example.com](https://example.com/@link)',
      '[[note|@alias]] and $@math$ and \\[@literal]', '',
      '<!-- biblio:vancouver -->', '', 'Generated @entry', '', '<!-- /biblio -->', '', '[@last]',
    ].join('\n');
    const model = citationDocument(EditorState.create({ doc: source }));
    expect(model.citations).toEqual([{ key: 'second', count: 2 }, { key: 'first', count: 1 }, { key: 'last', count: 1 }]);
    expect(model.style).toBe('vancouver');
    expect(model.clusters.map((cluster) => source.slice(cluster.from, cluster.to))).toEqual(['[@second; @first]', '@second', '[@last]']);
  });

  it('preserves the CSL prefix, page locator and suppress-author instruction in a grouped citation', () => {
    const model = parseCitationDocument('[see @alpha, pp. 12–14; -@beta]');
    expect(model.clusters[0].items).toEqual([
      { id: 'alpha', prefix: 'see ', locator: '12–14', label: 'page' },
      { id: 'beta', 'suppress-author': true },
    ]);
    expect(parseCitationDocument('[user@example.com]').citations).toEqual([]);
  });

  it('recognizes the native Typst cite calls generated by insertion without counting labels, raw code or comments', () => {
    const source = [
      '#cite(<first>) and #cite(<文献2024>) and #cite(<first>, form: "year") and @first',
      '@heading <heading>', '// #cite(<line-comment>)',
      '/* #cite(<outer>) /* #cite(<nested>) */ */',
      '```typst\n#cite(<raw>)\n```', '`#cite(<inline>)`', '#let example = "#cite(<string>)"',
    ].join('\n');
    const state = EditorState.create({ doc: source, extensions: [documentLanguageHint.of('typst')] });
    expect(extractCitations(state)).toEqual([{ key: 'first', count: 3 }, { key: '文献2024', count: 1 }]);
  });

  it('recognizes LaTeX groups and optional locators without counting comments or verbatim examples', () => {
    const source = [
      '\\cite{first, second} and \\parencite[p. 12]{first}',
      '% \\cite{comment}', '\\verb|\\cite{inline}|',
      '\\begin{verbatim}', '\\cite{block}', '\\end{verbatim}',
      '\\begin{minted}{tex}', '\\cite{minted}', '\\end{minted}',
      '\\% literal percent; \\cite{last}',
    ].join('\n');
    const state = EditorState.create({ doc: source, extensions: [documentLanguageHint.of('latex')] });
    expect(extractCitations(state)).toEqual([{ key: 'first', count: 2 }, { key: 'second', count: 1 }, { key: 'last', count: 1 }]);
  });

  it('frontmatter language overrides the initial document hint and programming files contain no writing citations', () => {
    expect(parseCitationDocument('---\nlanguage: typst\n---\n#cite(<real>)').citations).toEqual([{ key: 'real', count: 1 }]);
    expect(parseCitationDocument('decorator = "@code"', 'python').citations).toEqual([]);
  });

  it('bibliography actions ignore markers inside code and replace only the real comment region', () => {
    const example = '```md\n<!-- biblio:apa -->\nSample\n<!-- /biblio -->\n```';
    expect(detectBiblioStyle(example)).toBeNull();
    const real = '<!-- biblio:vancouver -->\n\nOld references\n\n<!-- /biblio -->';
    const source = `${example}\n\n${real}\n\nTail`;
    const edit = planBiblioEdit(source, 'REPLACEMENT');
    expect(source.slice(edit.from, edit.to)).toBe(real);
    expect(source.slice(0, edit.from)).toContain(example);
    expect(source.slice(edit.to)).toBe('\n\nTail');
  });
});
